### ISSUE TITLE
Add LDAP Login Support

### ISSUE THREAD

**Issue by laurin1** [phpservermon/phpservermon#206]
I might be able to write this myself, but wanted to see how much support was for this and / or request someone to add this feature.

**Comment by timurphy** [comment]
I'd like to see this feature included.

**Comment by viharm** [comment]
I have written a php LDAP authentication library for general use - [phpLDAPauth](https://bitbucket.org/viharm/phpldapauth) Will this help?

**Comment by sadortun** [comment]
That would be GREAT!  Do you think you can submit a PR that integrate your library?

**Comment by viharm** [comment]
Sure, I can try. Please point me to the login mechanism in your code so I can get a accelerated start.

**Comment by Kopertje** [comment]
How is this going?

**Comment by viharm** [comment]
Hi, I haven't worked on this much, but intend to over forthcoming the holiday period.

**Comment by sadortun** [comment]
@viharm any news ? Your contribution would be much appreciated !

**Comment by viharm** [comment]
Hi @sadortun , just studying the code; didn't go as quickly as I had hoped. My experience with PHP namespaces is limited, so taking longer than expected. If you can point me to the authentication hooks, it will definitely speed things up a bit :-)

**Comment by sadortun** [comment]
@dopeh Can you anser to @viharm  above ?  Thanks

**Comment by dopeh** [comment]
Hi,
All authentication is handled in the User service, more specifically the 
method 'loginWithPostData' at 
https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Service/User.php#L207 
is called to validate the login form. You could inject a separate LDAP 
authentication service into the User service, then check the global 
configuration for LDAP status, and when enabled use the LDAP service for 
user/password validation.
You could also extend the User service and override the necessary methods.

If you have any specific questions, feel free to get in touch. I haven't 
touched this code for quite a while but happy to help out.

**Comment by viharm** [comment]
Hi @dopeh , thanks for the pointer; this is exactly what I needed. I have looked at the service code, and it looks good. I will fork and carry out some trials. Will request some feedback once am in a position to share

**Comment by viharm** [comment]
I have created a draft module (https://gitlab.com/viharm/PsmLDAPauth/tree/dev) which does the authentication with LDAP. Wasn't sure where to locate it so have assumed that this should be in the vendor tree.

The PSM authentication subroutine (https://github.com/viharm/phpservermon/blob/f087c6eb25fd7b27a398b308ba1715f8a43e8940/src/psm/Service/User.php#L215), simply delegates the authentication to this module. If LDAP authentication is unsuccessful, it falls back to native auth (to ensure at least the built-in admin can login in case of LDAP failure).

Primary functionality works as per the following:

Takes username and password, checks with directory

1. LDAP auth success - Checks username in database (uses existing PDO connection object)
    a. Username exists - No action on DB; Passes control back to `loginWithPostdata` to get user by username for further processing.
    b. Username does not exist - (i). Adds user to DB with role `PSM_USER_USER`. (ii). Passes control back to `loginWithPostdata` to get user by username for further processing.
2. LDAP auth failure
    i. Falls back to native auth

Currently the module retrieves configuration for the directory service from a static config file. But this behaviour must change as the admin user should be able to configure the LDAP from the config UI.

Please help with the config UI and advise where this can be taken from. I believe the configuration in `psm_config` table.

If you agree, I can modify the behaviour to get details from this table.

**Comment by viharm** [comment]
The dependency on static configuration has now been completely removed. This module now depends on information passed to it as an argument.

Information is extracted from the DB by additional code in the user service subroutines (https://github.com/viharm/phpservermon/blob/88b2fab0bcd4e64247de9fceb58520a2d211091e/src/psm/Service/User.php#L215)

Added LDAP configuration section in the configuration UI (https://github.com/viharm/phpservermon/commit/b42ba6ec88ba17c2dc7a54efe8a8f71523c4a095 & https://github.com/viharm/phpservermon/commit/03e485c65822196c04a51bfeca94cd4112a2e032)

Added additional checks for variables (https://github.com/viharm/phpservermon/commit/320edb0fd8cfa8d8b08fdef091d4737ca0162da4 & https://github.com/viharm/phpservermon/commit/4efa0fdec924d5be0cc1344cf5bfc0d2a2b6b01f)

**Comment by viharm** [comment]
Before I submit a pull request, I request @dopeh or @sadortun to provide some guidance on how the submodule will be packaged. My assumption proposes that it be packaged as a vendor module, along with its underlying submodules.

This will mean that the PR will include the code changed in the core to accommodate the UI changes and references to the LDAP login mechanism.

Is this OK?

**Comment by viharm** [comment]
Added further functionality

* add AD domain settings (https://github.com/viharm/phpservermon/commit/4a5b58ee4ec5cd68d0f41a24531f3b8aefef40f7)
* checks to restrict directory groups (https://github.com/viharm/phpservermon/commit/fc68bbd88e388e0a4e973399e497ec7105862d65)
* default user role specification (https://github.com/viharm/phpservermon/commit/7c7c416b4ad47327188cd8f69b1e1205395815c0)

No "test LDAP" button/functionality in the configuration yet.

Preliminary tests indicate good compatibility with existing UI and database interaction.

Screenshot of the draft configuration page
![image](https://user-images.githubusercontent.com/2663937/29615044-5fe5b152-8804-11e7-8eb6-ca43d18b4516.png)
![image](https://user-images.githubusercontent.com/2663937/29615080-84b0263e-8804-11e7-9f9e-854d202bcdbb.png)

Will be ready for a PR after a few more tests.

**Comment by viharm** [comment]
@dopeh , @sadortun ,

I have submitted a pull request (#507) for this. Your feedback is welcome.

**Comment by ryannix123** [comment]
Thanks, @viharm! Can't wait to try it out. Any plans to add support for oAuth2?

**Comment by viharm** [comment]
@ryannix123 , glad to see the interest. Currently the underlying libraries do not have support for *OAuth 2.0*. However I will investigate if this can be put on the roadmap.

**Comment by viharm** [comment]
@ryannix123 , I have reviewed some high level documentation of concepts and deployment fof *OAuth 2.0*. Integrating this with *PsmLDAPauth* may be unwise. Moreover there are some well-mainteained implementations with built-in support for many providers (Google, MS, Github, etc.). My suggestion would be a separate module to interface with one of these libraries. I would love to work on this (and learn about *OAuth 2.0* in the process 😃 ); however due to limitations on my time, I would first like to focus on supportin this module (*PsmLDAPauth*).

I suggest opening a new issue to attract contributors (in case I don't get around to doing it quick enough 😛 ). If not I will certainly help.

**Comment by msbt** [comment]
Hi there!
Is there an eta on the LDAP login? I tried to use the pull request, but couldn't get it to work (probably my fault).

Best regards, M

**Comment by TimZ99** [comment]
Resolved the conflicts, maybe you have more luck now!

**Comment by msbt** [comment]
Thanks @TimZ99 - now I got all folders where they're supposed to be, but I can't login with ldap just yet.

With debug enabled it says "Binding successful" but then these show up:

` Warning: ldap_search(): Search: No such object in /app/data/public/test/vendor/PsmLDAPauth/phpLDAPauth/phpldapauth.php on line 438`

` Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in /app/data/public/test/vendor/PsmLDAPauth/phpLDAPauth/phpldapauth.php on line 445`

` Warning: ldap_free_result() expects parameter 1 to be resource, boolean given in /app/data/public/test/vendor/PsmLDAPauth/phpLDAPauth/phpldapauth.php on line 513`

Fyi, I'm trying to set this up using [Cloudron](https://cloudron.io/developer/addons/#ldap)

Best regards,
M

**Comment by viharm** [comment]
@msbt , are you still encountering these issues? If so, may I request a debug log from the *PsmLDAPauth* module?

**Comment by msbt** [comment]
@viharm , yes, still having issues. What exactly do I have to do to get that log? Or is it just the whole page with debug enabled that you want?

**Comment by msbt** [comment]
@viharm I'm a step further, but I can't get the group-filter to work:

```
Returning output
┌─────────────────────────────────────┐
│          $ag_DebugOutput            │
└─────────────────────────────────────┘
array (3) [
    'ky_User_Authenticated' => bool TRUE
    'ky_Group_Exists' => bool FALSE
    'ky_Group_ContainsUser' => bool FALSE
]
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Called from <ROOT>/test/vendor/PsmLDAPauth/phpLDAPauth/Lib/fl_Debug.lib.inc.php:87
```

Is there a way to ignore groups and just let anyone in that successfully authenticates?

**Comment by viharm** [comment]
@msbt , sorry for the delay in my response. I have been travelling significantly lately; and also preparing for a test.

Group membership is optional. Try leaving the field `Authorised directory group` blank. The authentication library should authenticate the user if this is not provided.

Let me know how it goes.

**Comment by msbt** [comment]
no problem @viharm, i tried removing it and now I'm getting this error:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value in /app/data/public/test/vendor/PsmLDAPauth/phpDBauth/phpdbauth.php:388 Stack trace: 
#0 /app/data/public/test/vendor/PsmLDAPauth/phpDBauth/phpdbauth.php(388): PDOStatement->execute() 
#1 /app/data/public/test/vendor/PsmLDAPauth/psmldapauth.php(128): fn__Database_Verify(Array, Array, 'pdo-mysql', NULL, Object(PDO)) 
#2 /app/data/public/test/src/psm/Service/User.php(233): psmldapauth('matthias', 'almostcompletepasswordvisible...', Array, Object(PDO)) 
#3 /app/data/public/test/src/psm/Module/User/Controller/LoginController.php(53): psm\Service\User->loginWithPostData('matthias', 'almostcompletepasswordvisible...', false) 
#4 /app/data/public/test/src/psm/Module/AbstractController.php(191): psm\Module\User\Controller\LoginController->executeLogin() 
#5 /app/data/public/test/src/psm/Module/AbstractController.php(162): psm\Module\AbstractController->runAction('login') 
#6 /app/data/public/test/src/psm/Router.php(102): psm\Module\AbstractControl in /app/data/public/test/vendor/PsmLDAPauth/phpDBauth/phpdbauth.php on line 388
```

after

```
Formulating SQL query to insert new record
Query formulated
┌──────────────────────────────────────────────────────────────────────────────┐
│                               $ag_DebugOutput                                │
└──────────────────────────────────────────────────────────────────────────────┘
string (108) "INSERT INTO `psm_users`
                ( `user_name`, `level` )
                VALUES ( 'matthias', '20' )"
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Called from <ROOT>/test/vendor/PsmLDAPauth/phpLDAPauth/Lib/fl_Debug.lib.inc.php:87

```

**Comment by viharm** [comment]
@msbt , trried to review the debug log. It appears that the fatal error indicates that MySQL is in strict mode, and expects a default value for the user's password when creating a new record for the user.

Please could you try to change line 108 in the file `psmldapauth.php`
from...
```php
$ar_Request['ky_UserPassword'] = NULL ;
```

to...
```php
$ar_Request['ky_UserPassword'] = '' ;
```

(notice the empty quotes).

Hopefully this should satisfy the strict requirements. Please let me knoww how it goes

**Comment by msbt** [comment]
@viharm I tried both, setting the ar_Request to '' and disabling strict mode, but neither of those had an effect on the error message, stayed the same in all versions that I've tried. I did have to rebuild the whole thing due to a crashed vm and 

> #6 /app/data/public/src/psm/Router.php(102): psm\Module\AbstractControl in /app/data/public/test/vendor/PsmLDAPauth/phpDBauth/phpdbauth.php on line 388

changed to 

> #6 /app/data/public/src/psm/Router.php(102): psm\Module\AbstractController->run('login') 
> #7 /app/data/public/in in /app/data/public/vendor/PsmLDAPauth/phpDBauth/phpdbauth.php on line 388

Not sure what I've done differently or which is the newer version ;)

Anything else I could try?

**Comment by msbt** [comment]
Ok I've been poking around in the db and changed the password field to NULL via

`ALTER TABLE 'psm_users' CHANGE 'password' 'password' VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'user\'s password in salted and hashed format';`

and tried to add the user manually like the script would with 

`INSERT INTO 'psm_users' ( 'user_name', 'level' ) VALUES ( 'matthias', '20' );`

Of course that didn't work since there are a lot of other fields that are not NULL:
 #1364 - Field 'name' doesn't have a default value
 #1364 - Field 'mobile' doesn't have a default value
 #1364 - Field 'pushover_key' doesn't have a default value
 #1364 - Field 'pushover_device' doesn't have a default value
 #1364 - Field 'telegram_id' doesn't have a default value
 #1364 - Field 'email' doesn't have a default value

So I ended up with that query:

`INSERT INTO 'psm_users' ( 'user_name', 'level', 'name', 'mobile', 'pushover_key', 'pushover_device', 'telegram_id', 'email' ) VALUES ( 'matthias', '20', 'matthias', '', '', '', '', 'mail@mydomain.com' );`

which went through. After that I could log in with the LDAP user, although I'm getting those error messages which disappear after a page refresh (and also when debug is set to FALSE):

> Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /app/data/public/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php on line 212
> 
> Warning: Cannot modify header information - headers already sent by (output started at /app/data/public/vendor/PsmLDAPauth/phpLDAPauth/Lib/kint/Kint.class.php:263) in /app/data/public/src/psm/Module/User/Controller/LoginController.php on line 58

So which is the way to go here to send this to production? ;)

**Comment by viharm** [comment]
@msbt , thanks for investigating further. your second message from 2-Jul shows progress. To debug further I will need a copy of the entire debug log.. Although the debugging tool redacts the passwords, please feel free to send it to me privately if you are concerned.

I will also try to replicated this on a test instance to see how the relation between the table structure and the LDAP module is influenced by the null password.

**Comment by viharm** [comment]
@msbt , I tried to do a fresh install, but could not reproduce the problem. My environment allows a NULL value for the password field. Please try to change the following in `/PSM/install/vendor/PsmLDAPauth/phpDBauth/phpdbauth.php`

Line 360 from
```php
( `" . $arg__Table [ "key__Table_ColumnUsername" ] . "`, `" . $arg__Table [ "key__Table_ColumnRole" ] . "` )
```

to
```php
( `" . $arg__Table [ "key__Table_ColumnUsername" ] . "`, `" . $arg__Table [ "key__Table_ColumnRole" ] . "`, `password" . "` )
```

Line 361 from
```php
VALUES ( '" . $arg__Common [ "key__Common_SearchUserKeyword" ] . "', '" . $arg__Table [ "key__Table_DefaultRoleValue" ] . "' )" ;
```

to
```php
VALUES ( '" . $arg__Common [ "key__Common_SearchUserKeyword" ] . "', '" . $arg__Table [ "key__Table_DefaultRoleValue" ] . "', 'REDACTED" . "' )" ;
```

Please let me know how it goes.

**Comment by viharm** [comment]
I noticed that this wasn't included in the latest release. I will update the dependencies to enable *Composer* compatibility/integration, and will update a fork to add the dependency in `composer.json`. Will this be ok?

**Comment by msbt** [comment]
Hey @viharm! Sorry for not replying, but I was preoccupied with another project which is now finished. I'll check out your suggestions in a bit! If you update the fork that would be even better, less tinkering from my side might solve the issues ;)

**Comment by viharm** [comment]
Albeit, later than planned, I have resumed work on this. Apologies for all the delays.
On initial inspection, the significant changes in 3.0 have caused some disconnects. I'm looking to clean up my changes and hopefully update the PR.

**Comment by viharm** [comment]
The base _PSM_ codebase has changed (but not significantly) since I first wrote this extension. I've started from scratch and have reached a prototype that works.

![Screenshot_2020-10-19 PsmLDAP test - Config](https://user-images.githubusercontent.com/2663937/96390141-2f905500-11ab-11eb-9a67-e7dc6ed136bb.png)

The issue that @msbt highlighted with the database fatal error due to null values has also been identified (see [issue 3](https://gitlab.com/viharm/PsmLDAPauth/-/issues/3) The default database configuration is that almost all fields in the users table are non-null. This will also be fixed before I submit my pull request.

**Comment by viharm** [comment]
@msbt, fork has been updated. Please see PR #507

**Comment by viharm** [comment]
@ryannix123 @Kopertje @timurphy @laurin1 
Sorry for the delay. I have now rewritten my changes on a freshly rebased dev branch from here (upstream).

Please could you check PR #507 .

**Comment by viharm** [comment]
@ryannix123 , @Kopertje , @timurphy , @msbt 

#507 has been tested by @red-erik on AD, and ready for merging. If you could test and provide feedback it would be very helpful.

**Comment by msbt** [comment]
@viharm thanks a lot, just tried, works like a charm!

**Comment by viharm** [comment]
@msbt , thanks for checking.
